name: Test

on: [ push ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        pyqt: [ 'PyQt5', 'PyQt6', 'PySide2', 'PySide6' ]
        os: [ ubuntu-latest ]
        python-version: [ '3.7', '3.10' ]
        include:
          - python-version: '3.8'
            pyqt: 'PySide6'
            os: macos-11
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - if: matrix.os == 'ubuntu-latest'
        name: Prepare GUI tests
        run: |
          sudo apt install libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0 x11-utils
          sudo apt update
          sudo apt install -y libpulse-mainloop-glib0 libegl1-mesa-dev libgstreamer-plugins-base1.0-dev libgstreamer1.0-dev
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test]
          pip install ${{ matrix.pyqt }}
      - name: Test with pytest
        run: |
          ./tst.sh
      - if: matrix.pyqt == 'PyQt5' && matrix.python-version == '3.7'
        name: coverage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install coveralls
          coveralls --service=github

  windows-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.10
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test]
          pip install ${{ matrix.pyqt }}
      - name: Test with pytest
        run: |
          python -m pytest test  --cov=qtuic --cov-report term -v --color=yes

  qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8
      - name: Lint with flake8
        run: |
          flake8 .
  
